### ISSUE TITLE
vsSelect DOM Exception

### ISSUE THREAD

**Issue by gianniskarmas** [lusaxweb/vuesax#424]
- Your OS: MacOS High Sierra
- Node.js: LTS 10.14.2
- Vuesax: 3.8.0
- Browser: Chrome
- Which package manager did you use for the install? Yarn

Using Nuxt, installed as a plugin and vuesax works with ssr.
Created a page and copied [the Single selection](https://lusaxweb.github.io/vuesax/components/selects.html#single-selection) example

It works but when leaving page I get:
```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at VueComponent.beforeDestroy (https://konpoli.eu/_nuxt/vendors.app.js:34728:12)
    at callHook (https://konpoli.eu/_nuxt/commons.app.js:14512:21)
    at VueComponent.Vue.$destroy (https://konpoli.eu/_nuxt/commons.app.js:14285:5)
    at destroy (https://konpoli.eu/_nuxt/commons.app.js:15750:27)
    at invokeDestroyHook (https://konpoli.eu/_nuxt/commons.app.js:17309:59)
    at invokeDestroyHook (https://konpoli.eu/_nuxt/commons.app.js:17314:9)
    at VueComponent.patch [as __patch__] (https://konpoli.eu/_nuxt/commons.app.js:17662:30)
    at VueComponent.Vue.$destroy (https://konpoli.eu/_nuxt/commons.app.js:14308:8)
    at destroy (https://konpoli.eu/_nuxt/commons.app.js:15750:27)
    at invokeDestroyHook (https://konpoli.eu/_nuxt/commons.app.js:17309:59)
```

**Comment by dker92** [comment]
I got the same problem...

**Comment by webafra** [comment]
I got the same problem...

**Comment by gianniskarmas** [comment]
@webafra unfortunately this is not a solution as the component is never destroyed, right?

**Comment by webafra** [comment]
@gianniskarmas The elements created on the page are automatically deleted and you do not need to use this code!
I do not know what the reason for using this code is!

**Comment by guastallaigor** [comment]
This was technically fixed here #345.
Please, see the response of @ccalvarez in #427.
Thank you.

**Comment by Pedrazl** [comment]
Same problem for me...

**Comment by gianniskarmas** [comment]
Already tried to make the change @webafra suggested in `node_modules/vuesax/dist/components/vsSelect.vue` as also in src folder but still can't fix it then tried to build but get error that `vue build has been deprecated`.
Any suggestions?

**Comment by Pedrazl** [comment]
Yeah, I had the same problem trying to fix another bug. It was imposible to compile the project to work on it, I sent an issue time ago about -- > https://github.com/lusaxweb/vuesax/issues/405 , but I'm still waiting.
I'm worried, no releases since October...

**Comment by ccalvarez** [comment]
In case one could build the library, what approach would be the recommended?, to publish own package in own npm account?  Or could it be possible to import the library without publishing a package?

I just ask because I have an application in production and I wanted to add error logging with Sentry.io, but with the current version of vuesax npm package, I would log a lot of this known errors.

Thanks.

**Comment by Pedrazl** [comment]
If you can build the library, you can save it into your project folders (the classic 'lib'), and set a reference in the initial load.

**Comment by luisDanielRoviraContreras** [comment]
Hello everyone, try to reproduce the error but I can not do it, you can give me an example to fix it, thank you very much to all

**Comment by Pedrazl** [comment]
Hi @luisDanielRoviraContreras , 
with the last release the problem has been fixed. 
thanks for your work
