### ISSUE TITLE
vs-select bug chrome 73 version

### ISSUE THREAD

**Issue by asmemo** [lusaxweb/vuesax#501]
After the Chrome 73 update, the select component works incorrectly. You can look at this page as an example https://lusaxweb.github.io/vuesax/components/selects.html#single-selection

**Comment by danyakov** [comment]
Are there any news? Problem is very serious.

**Comment by meyer59** [comment]
The same here, i hope it will be fixed soon

**Comment by ACVis** [comment]
Does anyone know what about Chrome 73 is causing this?

**Comment by contactabbas** [comment]
We are affected as well. It's a total loss of functionality. **our whole system is down**. Can you please treat this as P1?

**Comment by ashleymoogle** [comment]
I found a solution here : https://github.com/lusaxweb/vuesax/issues/511#issuecomment-481805129

**Comment by Jacrys** [comment]
Thanks to @ashleymoogle's suggestion, I think I was able to fix it.  I have an open PR (#537) that I believe fixes it.

**Comment by Jacrys** [comment]
@asmemo @danyakov @meyer59 @ACVis @contactabbas  Can you please check and verify if it is fixed?

**Comment by lk77** [comment]
Hello,
i still ave this issue on 3.8.62,
select is opening and closing just after.

**Comment by brunokunace** [comment]
hi everyone, i try now with chrome 74 and works fine, can you guys, test for me???

**Comment by Pedrazl** [comment]
I think this issue is fixed after version v3.8.75. 
@luisDanielRoviraContreras you can closed it.
Also I found other opened issues referred to the same thing that can be closed too --> (https://github.com/lusaxweb/vuesax/issues/511, https://github.com/lusaxweb/vuesax/issues/570)

**Comment by Tofandel** [comment]
Issue still present in latest version (3.11.17) this is getting ridiculous

**Comment by Tofandel** [comment]
![Peek 2020-07-29 16-43](https://user-images.githubusercontent.com/6115458/88814828-e687c080-d1ba-11ea-9897-9709e46c3bb3.gif)

**Comment by charithar** [comment]
I confirm that the exact same issue reported by @Tofandel exists in Google Chrome Version 84.0.4147.135 and Microsoft Edge Version 84.0.522.63. Don't see this behavior in Firefox 79.0 but when multiple drop down are open previous ones do not close automatically.

**Comment by lk77** [comment]
I have the issue still in chromium 84.
This issue needs to be fixed once and for all,
we were forced to remove vs-selects from our app and use the normal select instead,
vs-selects are totally unreliable.
