### ISSUE TITLE
Checkbox not working in Safari

### ISSUE THREAD

**Issue by YkkJeff** [lusaxweb/vuesax#532]
I put a watch property on the variable that is linked to my checkbox with v-model and click on the vs-checkbox and the value does not change in Safari.
On Chrome it is working well, changing the value on each checkbox click.

**Comment by Pajicc** [comment]
I'm having the same issue. Anyone working on this? 
@YkkJeff Any luck with solving it?

**Comment by YkkJeff** [comment]
Unfortunately, as no new version was released fixing the safari/firefox issues, we moved back to classic and custom components (checkboxes, switches, etc.).

**Comment by Pedrazl** [comment]
On firefox it seems to be fixed...not tried on Safari

**Comment by igorveremsky** [comment]
Create PR for this issue https://github.com/lusaxweb/vuesax/pull/725. For quick fix in builded source file you can change [`vuesax.common.js` file L3592-L3597](https://github.com/lusaxweb/vuesax/blob/master/dist/vuesax.common.js#L3592-L3597) to
```js
        change: (evt) => {
          this.toggleValue(evt)
        },
        // input: function input(evt) {
        //   _this.toggleValue(evt);
        // }
```

**Comment by igorveremsky** [comment]
@YkkJeff @Pajicc PR with fix merged to master. Please give a feedback is it works for you after update?

**Comment by chibuikemokoli** [comment]
It seems to be fixed on chrome for desktop, chrome and safari for smaller devices still have the issue.
